### ISSUE TITLE
Voice input function

### ISSUE THREAD

**Issue by MelanieSuette** [KL-Psychological-Methodology/ESMira#2]
Hi, I hope to have found the right chatroom here. 
We (MedUni Graz - Neurology and KFU Graz - Psychology) are currently working on conducting a study with patients from the LKH Graz that suffer from functional tremor. This means that they often are not able to use their hands very well, especially when typing on their phone. However, our study design requires them to type an answer of a few sentences to specific questions. So we were wondering if it would be possible to add a voice input function that would allow participants to dictate their answers instead of typing them?

**Comment by MelanieSuette** [comment]
Hi, thank you for your very quick answer!

That would be amazing, great to hear that this feature would be possible to implement! This addition would make the App perfect for our study design. We would like to start testing at the end of April/start of May. So the timing would also be spot on! :)

**Comment by JodliDev** [comment]
Hm if you want to start in the beginning of May, than that might be a bit too close.

I'll know more in mid April but I cant promise that it will be done in time.

As an alternative: Maybe the speech to text option of android and iOS would be a good plan B?

https://support.apple.com/de-at/guide/iphone/iph2c0651d2/ios

https://support.google.com/gboard/answer/2781851?hl=en&co=GENIE.Platform%3DAndroid

**Comment by MelanieSuette** [comment]
No worries! The speech to text option is a very good idea, thank you for your input. 
I am sure that we can still make the study design work, even if the App does not have the voice input function when we start testing. 
The study is meant to go on for about 6-10 months, so even if the feature is implemented sometime later within that time frame, we would be happy to include it then, in order to make the whole process easier for our patients. 
In the meantime, thank you for your help :)

**Comment by JodliDev** [comment]
Perfect. I will keep you posted, about my progress

**Comment by JodliDev** [comment]
Just as an update: I have finished implementing the new design and an "audio_record" item. Right now we are testing everything and, if there are no major issues, we should be ready to release it in about a week or so

**Comment by MelanieSuette** [comment]
Thank your for the update, that is great news! We are planning to start testing in about 2 weeks so we might even be able to use the tool from the start. Thank you for the quick implementation!

**Comment by JodliDev** [comment]
Ok. I have published the new design including support for a "record_audio" feature! :)

In order to use it in the admin interface, you need to update the server to the current "unstable" version (2.2.4-alpha.4).
You can select the unstable version with the dropdown ("update version") menu to the right in "server settings".

I advise you to test it yourself before using the "record_audio" item (and also keep an eye on the study data during data collection to catch errors early). I have tested it as far as I can. But since they have not been used by anyone else yet, I might have missed stuff.
Also keep in mind that they behave slightly different on iOS and Android. Mainly the file encoding is different (I am not an expert in audio files. So there might be things that need tweaking for specific use cases. For recording voices it should be fine though)

**Comment by MelanieSuette** [comment]
Thank you for the notification and the instructions!
We will start our testrun on both android and ios devices right next week and I will be back with the results hopefully by the end of the week! If everything works out, we well be able to use the voice input tool starting with the very first patient.
Thank you again for your quick help and the incredibly fast implementation!

**Comment by MelanieSuette** [comment]
Hello again, 
our IT-departement implemented the new update and after testing the voice input function on several devices, I am very happy to report that we did not encounter any problems at all! It worked easily and perfectly on all phones we tested. 
I would like to thank you again for this quick and very well-working solution!
Best regards! :)

**Comment by JodliDev** [comment]
I am very glad. I will close this issue now. If anything does not work as expected please let us know :)
