### ISSUE TITLE
Wiki on nginx configuration: replace "break" by "last"

### ISSUE THREAD

**Issue by gsalzer** [KL-Psychological-Methodology/ESMira#22]
I have configured an nginx server according to the wiki. I  found that all uris that needed rewriting, like `https://my_domain.xxx.yyy/app-1234-KEY`, actually were rewritten, but the resulting uri containing `index.php` was not executed, but the script was downloaded instead. Maybe there is some additional configuration not shown in the wiki that could make it work.

I resolved the issue by replacing, in each rewrite rule, the flag `break` by `last`. According to the documentation, `break` means that after rewriting, nginx stops looking for further locations (in the case of index.php, this means the location for executing php files), while the flag `last` makes nginx retry the configuration with the rewritten uri. So, in the first case the script index.php is returned verbatim, while in the second case the result of executing it is returned (which is what we want).

Attached you find my entire configuration (relying on letsencrypt). Replace MY_DOMAIN.SOME.WHERE by the actual domain.

[nginx-config.txt](https://github.com/user-attachments/files/17577377/nginx-config.txt)

**Comment by JodliDev** [comment]
Hello,
Sorry that it took so long to get back to you
Thank you so much for your suggestion. I fixed it in the wiki accordingly :)
